name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'    

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.allow_failures}}

    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2

        allow_failures: [false]

        include:
          - emacs_version: snapshot
            allow_failures: true

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Test the project
      run: |
        eldev -p -dtT -C test --expect 20
        eldev -dtT -C compile --set all --warnings-as-errors
