name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'    

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'

      - uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: '${{ runner.os }}-cargo-index-${{ hashFiles(''**/Cargo.lock'') }}'

      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path mxtodo-searcher/Cargo.toml

      - name: Check build artifact
        run: |
          filesize=$(du -sh ./mxtodo-searcher/target/debug/libmxtodo_searcher.so)
          echo "Artifact size: $filesize"

      - uses: actions/upload-artifact@v4
        with:
          name: mxtodo-searcher.so
          path: ./mxtodo-searcher/target/debug/libmxtodo_searcher.so
          if-no-files-found: error
  test:
    needs:
      - build
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.allow_failures}}

    strategy:
      matrix:
        emacs_version:
          - 28.1
          - 28.2
          - 29.1
          - 29.2

        allow_failures: [false]

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: mxtodo-searcher.so

      - name: Check for module artifact
        run: |
          if [ ! -f libmxtodo_searcher.so ]; then
              exit 1
          fi        

      - name: Rename module artifact
        run: mv libmxtodo_searcher.so mxtodo-searcher.so

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Test the project
        run: |
          eldev -p -dtT -C test --expect 5
          eldev -dtT -C compile --set all --warnings-as-errors
